<a href="https://colab.research.google.com/github/slee32323/Exploratory-Sales-Analysis-Pandas/blob/main/Exploratory_Sales_Data_Analysis_with_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. Import Pandas

In [ ]:
# Dataset
sales_data = {
 "Order_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
 111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
 "Customer": ["Sara", "Ali", "Mona", "Omar", "Sara", "Youssef", "Mona",
 "Ali", "Nour", "Omar", "Sara", "Nour", "Youssef", "Mona",
 "Ali", "Omar", "Sara", "Nour", "Youssef", "Mona"],
 "Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Mouse", "Laptop",
 "Monitor", "Keyboard", "Mouse", "Laptop", "Keyboard", "Monitor",
 "Mouse", "Laptop", "Monitor", "Keyboard", "Laptop", "Mouse",
 "Monitor", "Keyboard"],
 "Category": ["Computers", "Accessories", "Accessories", "Screens", "Accessories",
 "Computers", "Screens", "Accessories", "Accessories", "Computers",
 "Accessories", "Screens", "Accessories", "Computers", "Screens",
 "Accessories", "Computers", "Accessories", "Screens", "Accessories"],
 "Quantity": [1, 3, 2, 1, 5, 2, 1, 4, 2, 1, 3, 2, 6, 1, 2, 5, 1, 3, 2, 4],
 "Price": [25000, 500, 1200, 7000, 500, 25000, 7000, 1200, 500, 25000,
 1200, 7000, 500, 25000, 7000, 1200, 25000, 500, 7000, 1200],
 "City": ["Cairo", "Alexandria", "Cairo", "Giza", "Cairo", "Alexandria",
 "Giza", "Cairo", "Alexandria", "Giza", "Cairo", "Alexandria",
 "Cairo", "Giza", "Alexandria", "Cairo", "Giza", "Alexandria",
 "Cairo", "Giza"],
  "Payment_Method": ["Card", "Cash", "Card", "Card", "Cash", "Card", "Cash",
 "Card", "Cash", "Card", "Card", "Cash", "Card", "Card",
 "Cash", "Card", "Cash", "Card", "Cash", "Card"],
 "Salesperson": ["Ahmed", "Laila", "Ahmed", "Khaled", "Laila", "Ahmed",
 "Khaled", "Laila", "Ahmed", "Khaled", "Laila", "Ahmed",
 "Khaled", "Ahmed", "Laila", "Khaled", "Ahmed", "Laila",
 "Khaled", "Ahmed"]
}

In [ ]:
import pandas as pd

In [ ]:
# 2. Convert sales_data into DataFrame called df

In [ ]:
df = pd.DataFrame(sales_data)

In [ ]:
# 3. Display the Dataframe

In [ ]:
df

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson
0,101,Sara,Laptop,Computers,1,25000,Cairo,Card,Ahmed
1,102,Ali,Mouse,Accessories,3,500,Alexandria,Cash,Laila
2,103,Mona,Keyboard,Accessories,2,1200,Cairo,Card,Ahmed
3,104,Omar,Monitor,Screens,1,7000,Giza,Card,Khaled
4,105,Sara,Mouse,Accessories,5,500,Cairo,Cash,Laila
5,106,Youssef,Laptop,Computers,2,25000,Alexandria,Card,Ahmed
6,107,Mona,Monitor,Screens,1,7000,Giza,Cash,Khaled
7,108,Ali,Keyboard,Accessories,4,1200,Cairo,Card,Laila
8,109,Nour,Mouse,Accessories,2,500,Alexandria,Cash,Ahmed
9,110,Omar,Laptop,Computers,1,25000,Giza,Card,Khaled
10,111,Sara,Keyboard,Accessories,3,1200,Cairo,Card,Laila
11,112,Nour,Monitor,Screens,2,7000,Alexandria,Cash,Ahmed
12,113,Youssef,Mouse,Accessories,6,500,Cairo,Card,Khaled
13,114,Mona,Laptop,Computers,1,25000,Giza,Card,Ahmed
14,115,Ali,Monitor,Screens,2,7000,Alexandria,Cash,Laila
15,116,Omar,Keyboard,Accessories,5,1200,Cairo,Card,Khaled
16,117,Sara,Laptop,Computers,1,25000,Giza,Cash,Ahmed
17,118,Nour,Mouse,Accessories,3,500,Alexandria,Card,Laila
18,119,Youssef,Monitor,Screens,2,7000,Cairo,Cash,Khaled
19,120,Mona,Keyboard,Accessories,4,1200,Giza,Card,Ahmed

In [ ]:
#4. Display the first 5 rows.

In [ ]:
df.head(5)

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson
0,101,Sara,Laptop,Computers,1,25000,Cairo,Card,Ahmed
1,102,Ali,Mouse,Accessories,3,500,Alexandria,Cash,Laila
2,103,Mona,Keyboard,Accessories,2,1200,Cairo,Card,Ahmed
3,104,Omar,Monitor,Screens,1,7000,Giza,Card,Khaled
4,105,Sara,Mouse,Accessories,5,500,Cairo,Cash,Laila

In [ ]:
# 5. Display the last 5 rows

In [ ]:
df.tail(5)

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson
15,116,Omar,Keyboard,Accessories,5,1200,Cairo,Card,Khaled
16,117,Sara,Laptop,Computers,1,25000,Giza,Cash,Ahmed
17,118,Nour,Mouse,Accessories,3,500,Alexandria,Card,Laila
18,119,Youssef,Monitor,Screens,2,7000,Cairo,Cash,Khaled
19,120,Mona,Keyboard,Accessories,4,1200,Giza,Card,Ahmed

In [ ]:
#6. Check the number of rows and columns

In [ ]:
df.shape

(20, 9)

In [ ]:
#7. Display all column names

In [ ]:
df.columns

Index(['Order_ID', 'Customer', 'Product', 'Category', 'Quantity', 'Price',
       'City', 'Payment_Method', 'Salesperson'],
      dtype='object')

In [ ]:
# 8. Check the data type of every column

In [ ]:
df.dtypes

Order_ID           int64
Customer          object
Product           object
Category          object
Quantity           int64
Price              int64
City              object
Payment_Method    object
Salesperson       object
dtype: object

In [ ]:
# 9. Display only the Customer column

In [ ]:
df["Customer"]

0        Sara
1         Ali
2        Mona
3        Omar
4        Sara
5     Youssef
6        Mona
7         Ali
8        Nour
9        Omar
10       Sara
11       Nour
12    Youssef
13       Mona
14        Ali
15       Omar
16       Sara
17       Nour
18    Youssef
19       Mona
Name: Customer, dtype: object

In [ ]:
# 10. Display only the Product column

In [ ]:
df["Product"]

0       Laptop
1        Mouse
2     Keyboard
3      Monitor
4        Mouse
5       Laptop
6      Monitor
7     Keyboard
8        Mouse
9       Laptop
10    Keyboard
11     Monitor
12       Mouse
13      Laptop
14     Monitor
15    Keyboard
16      Laptop
17       Mouse
18     Monitor
19    Keyboard
Name: Product, dtype: object

In [ ]:
# 11. Display only the Price column

In [ ]:
df["Price"]

0     25000
1       500
2      1200
3      7000
4       500
5     25000
6      7000
7      1200
8       500
9     25000
10     1200
11     7000
12      500
13    25000
14     7000
15     1200
16    25000
17      500
18     7000
19     1200
Name: Price, dtype: int64

In [ ]:
# 12. Display the Customer, Product, and Price columns

In [ ]:
df[["Customer", "Product", "Price"]]

   Customer   Product  Price
0      Sara    Laptop  25000
1       Ali     Mouse    500
2      Mona  Keyboard   1200
3      Omar   Monitor   7000
4      Sara     Mouse    500
5   Youssef    Laptop  25000
6      Mona   Monitor   7000
7       Ali  Keyboard   1200
8      Nour     Mouse    500
9      Omar    Laptop  25000
10     Sara  Keyboard   1200
11     Nour   Monitor   7000
12  Youssef     Mouse    500
13     Mona    Laptop  25000
14      Ali   Monitor   7000
15     Omar  Keyboard   1200
16     Sara    Laptop  25000
17     Nour     Mouse    500
18  Youssef   Monitor   7000
19     Mona  Keyboard   1200

In [ ]:
# 13. Dispaly Product, Quantity, and City

In [ ]:
df[["Product", "Quantity", "City"]]

     Product  Quantity        City
0     Laptop         1       Cairo
1      Mouse         3  Alexandria
2   Keyboard         2       Cairo
3    Monitor         1        Giza
4      Mouse         5       Cairo
5     Laptop         2  Alexandria
6    Monitor         1        Giza
7   Keyboard         4       Cairo
8      Mouse         2  Alexandria
9     Laptop         1        Giza
10  Keyboard         3       Cairo
11   Monitor         2  Alexandria
12     Mouse         6       Cairo
13    Laptop         1        Giza
14   Monitor         2  Alexandria
15  Keyboard         5       Cairo
16    Laptop         1        Giza
17     Mouse         3  Alexandria
18   Monitor         2       Cairo
19  Keyboard         4        Giza

In [ ]:
# 14. Display Customer and Payment_Method

In [ ]:
df[["Customer", "Payment_Method"]]

   Customer Payment_Method
0      Sara           Card
1       Ali           Cash
2      Mona           Card
3      Omar           Card
4      Sara           Cash
5   Youssef           Card
6      Mona           Cash
7       Ali           Card
8      Nour           Cash
9      Omar           Card
10     Sara           Card
11     Nour           Cash
12  Youssef           Card
13     Mona           Card
14      Ali           Cash
15     Omar           Card
16     Sara           Cash
17     Nour           Card
18  Youssef           Cash
19     Mona           Card

In [ ]:
# 15. Store the Quantity column in a varaiable called quantities, then print it

In [ ]:
quantities = df["Quantity"]
print(quantities)

0     1
1     3
2     2
3     1
4     5
5     2
6     1
7     4
8     2
9     1
10    3
11    2
12    6
13    1
14    2
15    5
16    1
17    3
18    2
19    4
Name: Quantity, dtype: int64

In [ ]:
# 16. Create a new column called Total_Price. Calculate it as Quantity * Price

In [ ]:
df["Total_Price"] = df["Quantity"] * df["Price"]
print(df)

    Order_ID Customer   Product     Category  Quantity  Price        City  \
0        101     Sara    Laptop    Computers         1  25000       Cairo
1        102      Ali     Mouse  Accessories         3    500  Alexandria
2        103     Mona  Keyboard  Accessories         2   1200       Cairo
3        104     Omar   Monitor      Screens         1   7000        Giza
4        105     Sara     Mouse  Accessories         5    500       Cairo
5        106  Youssef    Laptop    Computers         2  25000  Alexandria
6        107     Mona   Monitor      Screens         1   7000        Giza
7        108      Ali  Keyboard  Accessories         4   1200       Cairo
8        109     Nour     Mouse  Accessories         2    500  Alexandria
9        110     Omar    Laptop    Computers         1  25000        Giza
10       111     Sara  Keyboard  Accessories         3   1200       Cairo
11       112     Nour   Monitor      Screens         2   7000  Alexandria
12       113  Youssef     Mouse  Accessories         6    500       Cairo
13       114     Mona    Laptop    Computers         1  25000        Giza
14       115      Ali   Monitor      Screens         2   7000  Alexandria
15       116     Omar  Keyboard  Accessories         5   1200       Cairo
16       117     Sara    Laptop    Computers         1  25000        Giza
17       118     Nour     Mouse  Accessories         3    500  Alexandria
18       119  Youssef   Monitor      Screens         2   7000       Cairo
19       120     Mona  Keyboard  Accessories         4   1200        Giza

   Payment_Method Salesperson  Total_Price
0            Card       Ahmed        25000
1            Cash       Laila         1500
2            Card       Ahmed         2400
3            Card      Khaled         7000
4            Cash       Laila         2500
5            Card       Ahmed        50000
6            Cash      Khaled         7000
7            Card       Laila         4800
8            Cash       Ahmed         1000
9            Card      Khaled        25000
10           Card       Laila         3600
11           Cash       Ahmed        14000
12           Card      Khaled         3000
13           Card       Ahmed        25000
14           Cash       Laila        14000
15           Card      Khaled         6000
16           Cash       Ahmed        25000
17           Card       Laila         1500
18           Cash      Khaled        14000
19           Card       Ahmed         4800

In [ ]:
# 17. Display only Product, Quantity, Price, and Total_Price

In [ ]:
df[["Product", "Quantity", "Price", "Total_Price"]]

     Product  Quantity  Price  Total_Price
0     Laptop         1  25000        25000
1      Mouse         3    500         1500
2   Keyboard         2   1200         2400
3    Monitor         1   7000         7000
4      Mouse         5    500         2500
5     Laptop         2  25000        50000
6    Monitor         1   7000         7000
7   Keyboard         4   1200         4800
8      Mouse         2    500         1000
9     Laptop         1  25000        25000
10  Keyboard         3   1200         3600
11   Monitor         2   7000        14000
12     Mouse         6    500         3000
13    Laptop         1  25000        25000
14   Monitor         2   7000        14000
15  Keyboard         5   1200         6000
16    Laptop         1  25000        25000
17     Mouse         3    500         1500
18   Monitor         2   7000        14000
19  Keyboard         4   1200         4800

In [ ]:
# 18. Find the total value of all sales

In [ ]:
df["Total_Price"].sum()

np.int64(237100)

In [ ]:
# 19. Find the average product price

In [ ]:
df["Price"].mean()

np.float64(8425.0)

In [ ]:
# 19. Find the average quantity ordered

In [ ]:
df["Quantity"].mean()

np.float64(2.55)

In [ ]:
# 21. Find the highest value in Total_Price

In [ ]:
df["Total_Price"].max()

50000

In [ ]:
# 22. Find the lowest value in Total_Price

In [ ]:
df["Total_Price"].min()

1000

In [ ]:
# 23. Display all orders where City is Cairo

In [ ]:
df[df["City"] == "Cairo"]

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price
0,101,Sara,Laptop,Computers,1,25000,Cairo,Card,Ahmed,25000
2,103,Mona,Keyboard,Accessories,2,1200,Cairo,Card,Ahmed,2400
4,105,Sara,Mouse,Accessories,5,500,Cairo,Cash,Laila,2500
7,108,Ali,Keyboard,Accessories,4,1200,Cairo,Card,Laila,4800
10,111,Sara,Keyboard,Accessories,3,1200,Cairo,Card,Laila,3600
12,113,Youssef,Mouse,Accessories,6,500,Cairo,Card,Khaled,3000
15,116,Omar,Keyboard,Accessories,5,1200,Cairo,Card,Khaled,6000
18,119,Youssef,Monitor,Screens,2,7000,Cairo,Cash,Khaled,14000

In [ ]:
# 24. Display all orders from Alexandria

In [ ]:
df[df["City"] == "Alexandria"]

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price
1,102,Ali,Mouse,Accessories,3,500,Alexandria,Cash,Laila,1500
5,106,Youssef,Laptop,Computers,2,25000,Alexandria,Card,Ahmed,50000
8,109,Nour,Mouse,Accessories,2,500,Alexandria,Cash,Ahmed,1000
11,112,Nour,Monitor,Screens,2,7000,Alexandria,Cash,Ahmed,14000
14,115,Ali,Monitor,Screens,2,7000,Alexandria,Cash,Laila,14000
17,118,Nour,Mouse,Accessories,3,500,Alexandria,Card,Laila,1500

In [ ]:
# 25. Display all orders where Product is Laptop

In [ ]:
df[df["Product"] == "Laptop"]

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price
0,101,Sara,Laptop,Computers,1,25000,Cairo,Card,Ahmed,25000
5,106,Youssef,Laptop,Computers,2,25000,Alexandria,Card,Ahmed,50000
9,110,Omar,Laptop,Computers,1,25000,Giza,Card,Khaled,25000
13,114,Mona,Laptop,Computers,1,25000,Giza,Card,Ahmed,25000
16,117,Sara,Laptop,Computers,1,25000,Giza,Cash,Ahmed,25000

In [ ]:
# 26. Display all orders where Product is Mouse.

In [ ]:
df[df["Product"] == "Mouse"]

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price
1,102,Ali,Mouse,Accessories,3,500,Alexandria,Cash,Laila,1500
4,105,Sara,Mouse,Accessories,5,500,Cairo,Cash,Laila,2500
8,109,Nour,Mouse,Accessories,2,500,Alexandria,Cash,Ahmed,1000
12,113,Youssef,Mouse,Accessories,6,500,Cairo,Card,Khaled,3000
17,118,Nour,Mouse,Accessories,3,500,Alexandria,Card,Laila,1500

In [ ]:
# 27. Display all orders where Quantity > 3

In [ ]:
df[df["Quantity"] > 3]

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price
4,105,Sara,Mouse,Accessories,5,500,Cairo,Cash,Laila,2500
7,108,Ali,Keyboard,Accessories,4,1200,Cairo,Card,Laila,4800
12,113,Youssef,Mouse,Accessories,6,500,Cairo,Card,Khaled,3000
15,116,Omar,Keyboard,Accessories,5,1200,Cairo,Card,Khaled,6000
19,120,Mona,Keyboard,Accessories,4,1200,Giza,Card,Ahmed,4800

In [ ]:
# 28. Display all orders where Price > 5000

In [ ]:
df[df["Price"] >5000]

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price
0,101,Sara,Laptop,Computers,1,25000,Cairo,Card,Ahmed,25000
3,104,Omar,Monitor,Screens,1,7000,Giza,Card,Khaled,7000
5,106,Youssef,Laptop,Computers,2,25000,Alexandria,Card,Ahmed,50000
6,107,Mona,Monitor,Screens,1,7000,Giza,Cash,Khaled,7000
9,110,Omar,Laptop,Computers,1,25000,Giza,Card,Khaled,25000
11,112,Nour,Monitor,Screens,2,7000,Alexandria,Cash,Ahmed,14000
13,114,Mona,Laptop,Computers,1,25000,Giza,Card,Ahmed,25000
14,115,Ali,Monitor,Screens,2,7000,Alexandria,Cash,Laila,14000
16,117,Sara,Laptop,Computers,1,25000,Giza,Cash,Ahmed,25000
18,119,Youssef,Monitor,Screens,2,7000,Cairo,Cash,Khaled,14000

In [ ]:
# 29. Display all orders where Payment_Method is Cash

In [ ]:
df[df["Payment_Method"] == "Cash"]

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price
1,102,Ali,Mouse,Accessories,3,500,Alexandria,Cash,Laila,1500
4,105,Sara,Mouse,Accessories,5,500,Cairo,Cash,Laila,2500
6,107,Mona,Monitor,Screens,1,7000,Giza,Cash,Khaled,7000
8,109,Nour,Mouse,Accessories,2,500,Alexandria,Cash,Ahmed,1000
11,112,Nour,Monitor,Screens,2,7000,Alexandria,Cash,Ahmed,14000
14,115,Ali,Monitor,Screens,2,7000,Alexandria,Cash,Laila,14000
16,117,Sara,Laptop,Computers,1,25000,Giza,Cash,Ahmed,25000
18,119,Youssef,Monitor,Screens,2,7000,Cairo,Cash,Khaled,14000

In [ ]:
# 30. Display all orders where Payment_Method is Card

In [ ]:
df[df["Payment_Method"] == "Card"]

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price
0,101,Sara,Laptop,Computers,1,25000,Cairo,Card,Ahmed,25000
2,103,Mona,Keyboard,Accessories,2,1200,Cairo,Card,Ahmed,2400
3,104,Omar,Monitor,Screens,1,7000,Giza,Card,Khaled,7000
5,106,Youssef,Laptop,Computers,2,25000,Alexandria,Card,Ahmed,50000
7,108,Ali,Keyboard,Accessories,4,1200,Cairo,Card,Laila,4800
9,110,Omar,Laptop,Computers,1,25000,Giza,Card,Khaled,25000
10,111,Sara,Keyboard,Accessories,3,1200,Cairo,Card,Laila,3600
12,113,Youssef,Mouse,Accessories,6,500,Cairo,Card,Khaled,3000
13,114,Mona,Laptop,Computers,1,25000,Giza,Card,Ahmed,25000
15,116,Omar,Keyboard,Accessories,5,1200,Cairo,Card,Khaled,6000
17,118,Nour,Mouse,Accessories,3,500,Alexandria,Card,Laila,1500
19,120,Mona,Keyboard,Accessories,4,1200,Giza,Card,Ahmed,4800

In [ ]:
# 31. Display orders where City is Cairo AND Quantity > 2

In [ ]:
df[(df["City"] == "Cairo") & (df["Quantity"] > 2)]

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price
4,105,Sara,Mouse,Accessories,5,500,Cairo,Cash,Laila,2500
7,108,Ali,Keyboard,Accessories,4,1200,Cairo,Card,Laila,4800
10,111,Sara,Keyboard,Accessories,3,1200,Cairo,Card,Laila,3600
12,113,Youssef,Mouse,Accessories,6,500,Cairo,Card,Khaled,3000
15,116,Omar,Keyboard,Accessories,5,1200,Cairo,Card,Khaled,6000

In [ ]:
# 32. Display orders where Product is Laptop AND City is Giza

In [ ]:
df[(df["Product"] == "Laptop") & (df["City"] =="Giza")]

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price
9,110,Omar,Laptop,Computers,1,25000,Giza,Card,Khaled,25000
13,114,Mona,Laptop,Computers,1,25000,Giza,Card,Ahmed,25000
16,117,Sara,Laptop,Computers,1,25000,Giza,Cash,Ahmed,25000

In [ ]:
# 33. Display orders where Payment_Method is Card AND Total_Price > 5000

In [ ]:
df[(df["Payment_Method"] == "Card") & (df["Total_Price"] > 5000)]

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price
0,101,Sara,Laptop,Computers,1,25000,Cairo,Card,Ahmed,25000
3,104,Omar,Monitor,Screens,1,7000,Giza,Card,Khaled,7000
5,106,Youssef,Laptop,Computers,2,25000,Alexandria,Card,Ahmed,50000
9,110,Omar,Laptop,Computers,1,25000,Giza,Card,Khaled,25000
13,114,Mona,Laptop,Computers,1,25000,Giza,Card,Ahmed,25000
15,116,Omar,Keyboard,Accessories,5,1200,Cairo,Card,Khaled,6000

In [ ]:
# 34. Display all orders where City is either Cairo OR Giza

In [ ]:
df[(df["City"] == "Cairo") | (df["City"] == "Giza")]

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price
0,101,Sara,Laptop,Computers,1,25000,Cairo,Card,Ahmed,25000
2,103,Mona,Keyboard,Accessories,2,1200,Cairo,Card,Ahmed,2400
3,104,Omar,Monitor,Screens,1,7000,Giza,Card,Khaled,7000
4,105,Sara,Mouse,Accessories,5,500,Cairo,Cash,Laila,2500
6,107,Mona,Monitor,Screens,1,7000,Giza,Cash,Khaled,7000
7,108,Ali,Keyboard,Accessories,4,1200,Cairo,Card,Laila,4800
9,110,Omar,Laptop,Computers,1,25000,Giza,Card,Khaled,25000
10,111,Sara,Keyboard,Accessories,3,1200,Cairo,Card,Laila,3600
12,113,Youssef,Mouse,Accessories,6,500,Cairo,Card,Khaled,3000
13,114,Mona,Laptop,Computers,1,25000,Giza,Card,Ahmed,25000
15,116,Omar,Keyboard,Accessories,5,1200,Cairo,Card,Khaled,6000
16,117,Sara,Laptop,Computers,1,25000,Giza,Cash,Ahmed,25000
18,119,Youssef,Monitor,Screens,2,7000,Cairo,Cash,Khaled,14000
19,120,Mona,Keyboard,Accessories,4,1200,Giza,Card,Ahmed,4800

In [ ]:
# 35. Display only Customer, Product, and Total_Price for orders where Total_Price > 10000

In [ ]:
df[df["Total_Price"] > 10000] [["Customer", "Product", "Total_Price"]]

   Customer  Product  Total_Price
0      Sara   Laptop        25000
5   Youssef   Laptop        50000
9      Omar   Laptop        25000
11     Nour  Monitor        14000
13     Mona   Laptop        25000
14      Ali  Monitor        14000
16     Sara   Laptop        25000
18  Youssef  Monitor        14000

In [ ]:
#36. Sort the DataFrame by Price from lowest to highest

In [ ]:
df.sort_values("Price", ascending=True)

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price
1,102,Ali,Mouse,Accessories,3,500,Alexandria,Cash,Laila,1500
4,105,Sara,Mouse,Accessories,5,500,Cairo,Cash,Laila,2500
12,113,Youssef,Mouse,Accessories,6,500,Cairo,Card,Khaled,3000
8,109,Nour,Mouse,Accessories,2,500,Alexandria,Cash,Ahmed,1000
17,118,Nour,Mouse,Accessories,3,500,Alexandria,Card,Laila,1500
10,111,Sara,Keyboard,Accessories,3,1200,Cairo,Card,Laila,3600
7,108,Ali,Keyboard,Accessories,4,1200,Cairo,Card,Laila,4800
15,116,Omar,Keyboard,Accessories,5,1200,Cairo,Card,Khaled,6000
19,120,Mona,Keyboard,Accessories,4,1200,Giza,Card,Ahmed,4800
2,103,Mona,Keyboard,Accessories,2,1200,Cairo,Card,Ahmed,2400
14,115,Ali,Monitor,Screens,2,7000,Alexandria,Cash,Laila,14000
11,112,Nour,Monitor,Screens,2,7000,Alexandria,Cash,Ahmed,14000
3,104,Omar,Monitor,Screens,1,7000,Giza,Card,Khaled,7000
18,119,Youssef,Monitor,Screens,2,7000,Cairo,Cash,Khaled,14000
6,107,Mona,Monitor,Screens,1,7000,Giza,Cash,Khaled,7000
5,106,Youssef,Laptop,Computers,2,25000,Alexandria,Card,Ahmed,50000
13,114,Mona,Laptop,Computers,1,25000,Giza,Card,Ahmed,25000
9,110,Omar,Laptop,Computers,1,25000,Giza,Card,Khaled,25000
0,101,Sara,Laptop,Computers,1,25000,Cairo,Card,Ahmed,25000
16,117,Sara,Laptop,Computers,1,25000,Giza,Cash,Ahmed,25000

In [ ]:
# 37. Sort the DatFrame by Price from highest to lowest

In [ ]:
df.sort_values("Price", ascending=False)

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price
0,101,Sara,Laptop,Computers,1,25000,Cairo,Card,Ahmed,25000
16,117,Sara,Laptop,Computers,1,25000,Giza,Cash,Ahmed,25000
9,110,Omar,Laptop,Computers,1,25000,Giza,Card,Khaled,25000
5,106,Youssef,Laptop,Computers,2,25000,Alexandria,Card,Ahmed,50000
13,114,Mona,Laptop,Computers,1,25000,Giza,Card,Ahmed,25000
14,115,Ali,Monitor,Screens,2,7000,Alexandria,Cash,Laila,14000
3,104,Omar,Monitor,Screens,1,7000,Giza,Card,Khaled,7000
18,119,Youssef,Monitor,Screens,2,7000,Cairo,Cash,Khaled,14000
11,112,Nour,Monitor,Screens,2,7000,Alexandria,Cash,Ahmed,14000
6,107,Mona,Monitor,Screens,1,7000,Giza,Cash,Khaled,7000
19,120,Mona,Keyboard,Accessories,4,1200,Giza,Card,Ahmed,4800
2,103,Mona,Keyboard,Accessories,2,1200,Cairo,Card,Ahmed,2400
7,108,Ali,Keyboard,Accessories,4,1200,Cairo,Card,Laila,4800
15,116,Omar,Keyboard,Accessories,5,1200,Cairo,Card,Khaled,6000
10,111,Sara,Keyboard,Accessories,3,1200,Cairo,Card,Laila,3600
1,102,Ali,Mouse,Accessories,3,500,Alexandria,Cash,Laila,1500
8,109,Nour,Mouse,Accessories,2,500,Alexandria,Cash,Ahmed,1000
4,105,Sara,Mouse,Accessories,5,500,Cairo,Cash,Laila,2500
12,113,Youssef,Mouse,Accessories,6,500,Cairo,Card,Khaled,3000
17,118,Nour,Mouse,Accessories,3,500,Alexandria,Card,Laila,1500

In [ ]:
# 38. Sort the DataFrame by Quantity from highest to lowest

In [ ]:
df.sort_values("Quantity", ascending=False)

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price
12,113,Youssef,Mouse,Accessories,6,500,Cairo,Card,Khaled,3000
4,105,Sara,Mouse,Accessories,5,500,Cairo,Cash,Laila,2500
15,116,Omar,Keyboard,Accessories,5,1200,Cairo,Card,Khaled,6000
7,108,Ali,Keyboard,Accessories,4,1200,Cairo,Card,Laila,4800
19,120,Mona,Keyboard,Accessories,4,1200,Giza,Card,Ahmed,4800
17,118,Nour,Mouse,Accessories,3,500,Alexandria,Card,Laila,1500
10,111,Sara,Keyboard,Accessories,3,1200,Cairo,Card,Laila,3600
1,102,Ali,Mouse,Accessories,3,500,Alexandria,Cash,Laila,1500
18,119,Youssef,Monitor,Screens,2,7000,Cairo,Cash,Khaled,14000
14,115,Ali,Monitor,Screens,2,7000,Alexandria,Cash,Laila,14000
2,103,Mona,Keyboard,Accessories,2,1200,Cairo,Card,Ahmed,2400
5,106,Youssef,Laptop,Computers,2,25000,Alexandria,Card,Ahmed,50000
8,109,Nour,Mouse,Accessories,2,500,Alexandria,Cash,Ahmed,1000
11,112,Nour,Monitor,Screens,2,7000,Alexandria,Cash,Ahmed,14000
3,104,Omar,Monitor,Screens,1,7000,Giza,Card,Khaled,7000
0,101,Sara,Laptop,Computers,1,25000,Cairo,Card,Ahmed,25000
9,110,Omar,Laptop,Computers,1,25000,Giza,Card,Khaled,25000
6,107,Mona,Monitor,Screens,1,7000,Giza,Cash,Khaled,7000
13,114,Mona,Laptop,Computers,1,25000,Giza,Card,Ahmed,25000
16,117,Sara,Laptop,Computers,1,25000,Giza,Cash,Ahmed,25000

In [ ]:
# 39. Sort the DataFrame by Total_Price from highest to lowest

In [ ]:
df.sort_values("Total_Price", ascending=False)

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price
5,106,Youssef,Laptop,Computers,2,25000,Alexandria,Card,Ahmed,50000
0,101,Sara,Laptop,Computers,1,25000,Cairo,Card,Ahmed,25000
9,110,Omar,Laptop,Computers,1,25000,Giza,Card,Khaled,25000
16,117,Sara,Laptop,Computers,1,25000,Giza,Cash,Ahmed,25000
13,114,Mona,Laptop,Computers,1,25000,Giza,Card,Ahmed,25000
14,115,Ali,Monitor,Screens,2,7000,Alexandria,Cash,Laila,14000
11,112,Nour,Monitor,Screens,2,7000,Alexandria,Cash,Ahmed,14000
18,119,Youssef,Monitor,Screens,2,7000,Cairo,Cash,Khaled,14000
3,104,Omar,Monitor,Screens,1,7000,Giza,Card,Khaled,7000
6,107,Mona,Monitor,Screens,1,7000,Giza,Cash,Khaled,7000
15,116,Omar,Keyboard,Accessories,5,1200,Cairo,Card,Khaled,6000
19,120,Mona,Keyboard,Accessories,4,1200,Giza,Card,Ahmed,4800
7,108,Ali,Keyboard,Accessories,4,1200,Cairo,Card,Laila,4800
10,111,Sara,Keyboard,Accessories,3,1200,Cairo,Card,Laila,3600
12,113,Youssef,Mouse,Accessories,6,500,Cairo,Card,Khaled,3000
4,105,Sara,Mouse,Accessories,5,500,Cairo,Cash,Laila,2500
2,103,Mona,Keyboard,Accessories,2,1200,Cairo,Card,Ahmed,2400
1,102,Ali,Mouse,Accessories,3,500,Alexandria,Cash,Laila,1500
17,118,Nour,Mouse,Accessories,3,500,Alexandria,Card,Laila,1500
8,109,Nour,Mouse,Accessories,2,500,Alexandria,Cash,Ahmed,1000

In [ ]:
# 40. Display the 5 orders with the highest Total_Price

In [ ]:
df.sort_values("Total_Price", ascending=False).head(5)

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price
5,106,Youssef,Laptop,Computers,2,25000,Alexandria,Card,Ahmed,50000
0,101,Sara,Laptop,Computers,1,25000,Cairo,Card,Ahmed,25000
9,110,Omar,Laptop,Computers,1,25000,Giza,Card,Khaled,25000
16,117,Sara,Laptop,Computers,1,25000,Giza,Cash,Ahmed,25000
13,114,Mona,Laptop,Computers,1,25000,Giza,Card,Ahmed,25000

In [ ]:
# 41. Find how many orders each product appear in.

In [ ]:
df["Product"].value_counts()

Product
Laptop      5
Mouse       5
Keyboard    5
Monitor     5
Name: count, dtype: int64

In [ ]:
# 42. Find how many orders came from each city

In [ ]:
df["City"].value_counts()

City
Cairo         8
Alexandria    6
Giza          6
Name: count, dtype: int64

In [ ]:
# 43. Find how many times each payment method was used

In [ ]:
df["Payment_Method"].value_counts()

Payment_Method
Card    12
Cash     8
Name: count, dtype: int64

In [ ]:
# 44. Find how many orders each salesperson handeld

In [ ]:
df["Salesperson"].value_counts()

Salesperson
Ahmed     8
Laila     6
Khaled    6
Name: count, dtype: int64

In [ ]:
# 45. Find how many orders each customer made

In [ ]:
df["Customer"].value_counts()

Customer
Sara       4
Mona       4
Ali        3
Omar       3
Youssef    3
Nour       3
Name: count, dtype: int64

In [ ]:
# 46. Apply the order_size() function to the Quantity column and create a new column called Order_Size

In [ ]:
def order_size(quantity):
  if quantity >= 4:
    return "Large"
  else:
    return "Small"

df["Order_Size"] = df["Quantity"].apply(order_size)
df

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price,Order_Size
0,101,Sara,Laptop,Computers,1,25000,Cairo,Card,Ahmed,25000,Small
1,102,Ali,Mouse,Accessories,3,500,Alexandria,Cash,Laila,1500,Small
2,103,Mona,Keyboard,Accessories,2,1200,Cairo,Card,Ahmed,2400,Small
3,104,Omar,Monitor,Screens,1,7000,Giza,Card,Khaled,7000,Small
4,105,Sara,Mouse,Accessories,5,500,Cairo,Cash,Laila,2500,Large
5,106,Youssef,Laptop,Computers,2,25000,Alexandria,Card,Ahmed,50000,Small
6,107,Mona,Monitor,Screens,1,7000,Giza,Cash,Khaled,7000,Small
7,108,Ali,Keyboard,Accessories,4,1200,Cairo,Card,Laila,4800,Large
8,109,Nour,Mouse,Accessories,2,500,Alexandria,Cash,Ahmed,1000,Small
9,110,Omar,Laptop,Computers,1,25000,Giza,Card,Khaled,25000,Small
10,111,Sara,Keyboard,Accessories,3,1200,Cairo,Card,Laila,3600,Small
11,112,Nour,Monitor,Screens,2,7000,Alexandria,Cash,Ahmed,14000,Small
12,113,Youssef,Mouse,Accessories,6,500,Cairo,Card,Khaled,3000,Large
13,114,Mona,Laptop,Computers,1,25000,Giza,Card,Ahmed,25000,Small
14,115,Ali,Monitor,Screens,2,7000,Alexandria,Cash,Laila,14000,Small
15,116,Omar,Keyboard,Accessories,5,1200,Cairo,Card,Khaled,6000,Large
16,117,Sara,Laptop,Computers,1,25000,Giza,Cash,Ahmed,25000,Small
17,118,Nour,Mouse,Accessories,3,500,Alexandria,Card,Laila,1500,Small
18,119,Youssef,Monitor,Screens,2,7000,Cairo,Cash,Khaled,14000,Small
19,120,Mona,Keyboard,Accessories,4,1200,Giza,Card,Ahmed,4800,Large

In [ ]:
# 47. Display Product, Quantity, and Order_Size

In [ ]:
df[["Product", "Quantity", "Order_Size"]]

     Product  Quantity Order_Size
0     Laptop         1      Small
1      Mouse         3      Small
2   Keyboard         2      Small
3    Monitor         1      Small
4      Mouse         5      Large
5     Laptop         2      Small
6    Monitor         1      Small
7   Keyboard         4      Large
8      Mouse         2      Small
9     Laptop         1      Small
10  Keyboard         3      Small
11   Monitor         2      Small
12     Mouse         6      Large
13    Laptop         1      Small
14   Monitor         2      Small
15  Keyboard         5      Large
16    Laptop         1      Small
17     Mouse         3      Small
18   Monitor         2      Small
19  Keyboard         4      Large

In [ ]:
# 48. Count how many orders are Large and howm nay are Small

In [ ]:
df["Order_Size"].value_counts()

Order_Size
Small    15
Large     5
Name: count, dtype: int64

In [ ]:
# 49. Apply the Payment_message() function to Payment_Method and create a new column called Payment_Type

In [ ]:
def payment_message(payment):
  if payment == "Card":
    return "Electronic Payment"
  else:
    return "Cash Payment"
df["Payment_Type"] =df["Payment_Method"].apply(payment_message)
df

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price,Order_Size,Payment_Type
0,101,Sara,Laptop,Computers,1,25000,Cairo,Card,Ahmed,25000,Small,Electronic Payment
1,102,Ali,Mouse,Accessories,3,500,Alexandria,Cash,Laila,1500,Small,Cash Payment
2,103,Mona,Keyboard,Accessories,2,1200,Cairo,Card,Ahmed,2400,Small,Electronic Payment
3,104,Omar,Monitor,Screens,1,7000,Giza,Card,Khaled,7000,Small,Electronic Payment
4,105,Sara,Mouse,Accessories,5,500,Cairo,Cash,Laila,2500,Large,Cash Payment
5,106,Youssef,Laptop,Computers,2,25000,Alexandria,Card,Ahmed,50000,Small,Electronic Payment
6,107,Mona,Monitor,Screens,1,7000,Giza,Cash,Khaled,7000,Small,Cash Payment
7,108,Ali,Keyboard,Accessories,4,1200,Cairo,Card,Laila,4800,Large,Electronic Payment
8,109,Nour,Mouse,Accessories,2,500,Alexandria,Cash,Ahmed,1000,Small,Cash Payment
9,110,Omar,Laptop,Computers,1,25000,Giza,Card,Khaled,25000,Small,Electronic Payment
10,111,Sara,Keyboard,Accessories,3,1200,Cairo,Card,Laila,3600,Small,Electronic Payment
11,112,Nour,Monitor,Screens,2,7000,Alexandria,Cash,Ahmed,14000,Small,Cash Payment
12,113,Youssef,Mouse,Accessories,6,500,Cairo,Card,Khaled,3000,Large,Electronic Payment
13,114,Mona,Laptop,Computers,1,25000,Giza,Card,Ahmed,25000,Small,Electronic Payment
14,115,Ali,Monitor,Screens,2,7000,Alexandria,Cash,Laila,14000,Small,Cash Payment
15,116,Omar,Keyboard,Accessories,5,1200,Cairo,Card,Khaled,6000,Large,Electronic Payment
16,117,Sara,Laptop,Computers,1,25000,Giza,Cash,Ahmed,25000,Small,Cash Payment
17,118,Nour,Mouse,Accessories,3,500,Alexandria,Card,Laila,1500,Small,Electronic Payment
18,119,Youssef,Monitor,Screens,2,7000,Cairo,Cash,Khaled,14000,Small,Cash Payment
19,120,Mona,Keyboard,Accessories,4,1200,Giza,Card,Ahmed,4800,Large,Electronic Payment

In [ ]:
# 50. Display Payment_Method and Payment_Type

In [ ]:
df[["Payment_Method", "Payment_Type"]]

   Payment_Method        Payment_Type
0            Card  Electronic Payment
1            Cash        Cash Payment
2            Card  Electronic Payment
3            Card  Electronic Payment
4            Cash        Cash Payment
5            Card  Electronic Payment
6            Cash        Cash Payment
7            Card  Electronic Payment
8            Cash        Cash Payment
9            Card  Electronic Payment
10           Card  Electronic Payment
11           Cash        Cash Payment
12           Card  Electronic Payment
13           Card  Electronic Payment
14           Cash        Cash Payment
15           Card  Electronic Payment
16           Cash        Cash Payment
17           Card  Electronic Payment
18           Cash        Cash Payment
19           Card  Electronic Payment

In [ ]:
# 51. Write a function called price_level(). If Price > 5000 return "Expensive", otherwise return "Affordable". Apply it to Price and create Price_Level.

In [ ]:
def price_level(price):
  if price > 5000:
    return "Expensive"
  else:
    return "Affordable"

df["Price_Level"] = df["Price"].apply(price_level)

In [ ]:
# 52. Display Product, Price, and Price_Level

In [ ]:
df[["Product", "Price", "Price_Level"]]

     Product  Price Price_Level
0     Laptop  25000   Expensive
1      Mouse    500  Affordable
2   Keyboard   1200  Affordable
3    Monitor   7000   Expensive
4      Mouse    500  Affordable
5     Laptop  25000   Expensive
6    Monitor   7000   Expensive
7   Keyboard   1200  Affordable
8      Mouse    500  Affordable
9     Laptop  25000   Expensive
10  Keyboard   1200  Affordable
11   Monitor   7000   Expensive
12     Mouse    500  Affordable
13    Laptop  25000   Expensive
14   Monitor   7000   Expensive
15  Keyboard   1200  Affordable
16    Laptop  25000   Expensive
17     Mouse    500  Affordable
18   Monitor   7000   Expensive
19  Keyboard   1200  Affordable

In [ ]:
# 53. Find how many products were classified as Expensive and Affordable

In [ ]:
df["Price_Level"].value_counts()

Price_Level
Expensive     10
Affordable    10
Name: count, dtype: int64

In [ ]:
# 54. Group the data by Product and find the a verage price

In [ ]:
df.groupby("Product")["Price"].mean()

Product
Keyboard     1200.0
Laptop      25000.0
Monitor      7000.0
Mouse         500.0
Name: Price, dtype: float64

In [ ]:
# 55. Group the data by Product and find the total quantity sold.

In [ ]:
df.groupby("Product")["Quantity"].sum()

Product
Keyboard    18
Laptop       6
Monitor      8
Mouse       19
Name: Quantity, dtype: int64

In [ ]:
# 56. Group the data by City and find the total quantity sold

In [ ]:
df.groupby("City")["Quantity"].sum()

City
Alexandria    14
Cairo         28
Giza           9
Name: Quantity, dtype: int64

In [ ]:
# 57. Group the data by City and find total sales using Total_Price

In [ ]:
df.groupby("City")["Total_Price"].sum()

City
Alexandria    82000
Cairo         61300
Giza          93800
Name: Total_Price, dtype: int64

In [ ]:
# 58. Group the data by Customer and find how much each customer spent in total

In [ ]:
df.groupby("Customer")["Total_Price"].sum()

Customer
Ali        20300
Mona       39200
Nour       16500
Omar       38000
Sara       56100
Youssef    67000
Name: Total_Price, dtype: int64

In [ ]:
# 59. Group the data by Salesperson and find total sales made by each salesperson

In [ ]:
df.groupby("Salesperson")["Total_Price"].sum()

Salesperson
Ahmed     147200
Khaled     62000
Laila      27900
Name: Total_Price, dtype: int64

In [ ]:
# 60. Group the data by Payment_Method and find the average Total_Price

In [ ]:
df.groupby("Payment_Method")["Total_Price"].mean()

Payment_Method
Card    13175.0
Cash     9875.0
Name: Total_Price, dtype: float64

In [ ]:
# 61. Find the total quantity sold for every Product. The result shouhld show only Product and Quantity

In [ ]:
df.groupby("Product")["Quantity"].sum()

Product
Keyboard    18
Laptop       6
Monitor      8
Mouse       19
Name: Quantity, dtype: int64

In [ ]:
# 62.Find total sales for every City

In [ ]:
df.groupby("City")["Total_Price"].sum()

City
Alexandria    82000
Cairo         61300
Giza          93800
Name: Total_Price, dtype: int64

In [ ]:
# 63. Find the average quantity ordered by each Customer

In [ ]:
df.groupby("Customer")["Quantity"].mean()

Customer
Ali        3.000000
Mona       2.000000
Nour       2.333333
Omar       2.333333
Sara       2.500000
Youssef    3.333333
Name: Quantity, dtype: float64

In [ ]:
# 64. Find the average order value for every Salesperson.

In [ ]:
df.groupby("Salesperson")["Total_Price"].mean()

Salesperson
Ahmed     18400.000000
Khaled    10333.333333
Laila      4650.000000
Name: Total_Price, dtype: float64

In [ ]:
# 65. Find total sales for each Category

In [ ]:
df.groupby("Category")["Total_Price"].sum()

Category
Accessories     31100
Computers      150000
Screens         56000
Name: Total_Price, dtype: int64

In [ ]:
# 66. Group by City and Product, then find the total quantity sold.

In [ ]:
df.groupby(["City", "Product"])["Quantity"].sum()

City        Product
Alexandria  Laptop       2
            Monitor      4
            Mouse        8
Cairo       Keyboard    14
            Laptop       1
            Monitor      2
            Mouse       11
Giza        Keyboard     4
            Laptop       3
            Monitor      2
Name: Quantity, dtype: int64

In [ ]:
# 67. Group by Salesperson and Product, then find the total quantity sold

In [ ]:
df.groupby(["Salesperson", "Product"])["Quantity"].sum()

Salesperson  Product
Ahmed        Keyboard     6
             Laptop       5
             Monitor      2
             Mouse        2
Khaled       Keyboard     5
             Laptop       1
             Monitor      4
             Mouse        6
Laila        Keyboard     7
             Monitor      2
             Mouse       11
Name: Quantity, dtype: int64

In [ ]:
# 68. Group by City and Payment_Method, then find total sales

In [ ]:
df.groupby(["City", "Payment_Method"])["Total_Price"].sum()

City        Payment_Method
Alexandria  Card              51500
            Cash              30500
Cairo       Card              44800
            Cash              16500
Giza        Card              61800
            Cash              32000
Name: Total_Price, dtype: int64

In [ ]:
# 69. Group by Customer and Product, hten find the total amount spent

In [ ]:
df.groupby(["Customer", "Product"])["Total_Price"].sum()

Customer  Product
Ali       Keyboard     4800
          Monitor     14000
          Mouse        1500
Mona      Keyboard     7200
          Laptop      25000
          Monitor      7000
Nour      Monitor     14000
          Mouse        2500
Omar      Keyboard     6000
          Laptop      25000
          Monitor      7000
Sara      Keyboard     3600
          Laptop      50000
          Mouse        2500
Youssef   Laptop      50000
          Monitor     14000
          Mouse        3000
Name: Total_Price, dtype: int64

In [ ]:
# 70. Which product had the highest total quantity sold

In [ ]:
df.groupby("Product")["Quantity"].sum().sort_values(ascending=False).head(1)
# Mouse had the highest total quantity sold, with 19 units

Product
Mouse    19
Name: Quantity, dtype: int64

In [ ]:
# 71. Which city generated the highest total sales?

In [ ]:
df.groupby("City")["Total_Price"].sum().sort_values(ascending=False).head(1)
# Giza generated the highest total sales, with 93,800.

City
Giza    93800
Name: Total_Price, dtype: int64

In [ ]:
# 72. Which salesperson generated the highest sales?

In [ ]:
df.groupby("Salesperson")["Total_Price"].sum().sort_values(ascending=False).head(1)
#Ahmed generated the highest sales

Salesperson
Ahmed    147200
Name: Total_Price, dtype: int64

In [ ]:
# 73. Which customer spend the most money?

In [ ]:
df.groupby("Customer")["Total_Price"].sum().sort_values(ascending=False).head(1)
# Youssef spend the most money with a totla of 67,000

Customer
Youssef    67000
Name: Total_Price, dtype: int64

In [ ]:
# 74. Which payment mehtod generated more sales?

In [ ]:
df.groupby("Payment_Method")["Total_Price"].sum().sort_values(ascending=False).head(1)
# Card generated more sales, with total sales of 158,100

Payment_Method
Card    158100
Name: Total_Price, dtype: int64

In [ ]:
# 75. Which product generated the most moeny?

In [ ]:
df.groupby("Product")["Total_Price"].sum().sort_values(ascending=False).head(1)
# Laptop generated the most money, with total sales of 150,000

Product
Laptop    150000
Name: Total_Price, dtype: int64

In [ ]:
# 76. Create a new DataFrame containning only orders where Total_Price > 5000 AND Payment_Method is Card. Dispaly it

In [ ]:
filtered_df = df[(df["Total_Price"] > 5000) & (df["Payment_Method"] == "Card")]
filtered_df

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price,Order_Size,Payment_Type,Price_Level
0,101,Sara,Laptop,Computers,1,25000,Cairo,Card,Ahmed,25000,Small,Electronic Payment,Expensive
3,104,Omar,Monitor,Screens,1,7000,Giza,Card,Khaled,7000,Small,Electronic Payment,Expensive
5,106,Youssef,Laptop,Computers,2,25000,Alexandria,Card,Ahmed,50000,Small,Electronic Payment,Expensive
9,110,Omar,Laptop,Computers,1,25000,Giza,Card,Khaled,25000,Small,Electronic Payment,Expensive
13,114,Mona,Laptop,Computers,1,25000,Giza,Card,Ahmed,25000,Small,Electronic Payment,Expensive
15,116,Omar,Keyboard,Accessories,5,1200,Cairo,Card,Khaled,6000,Large,Electronic Payment,Affordable

In [ ]:
# 77. From this filtered DataFrame, display only Customer, Product, City, and Total_Price.

In [ ]:
filtered_df[["Customer", "Product", "City", "Total_Price"]]

   Customer   Product        City  Total_Price
0      Sara    Laptop       Cairo        25000
3      Omar   Monitor        Giza         7000
5   Youssef    Laptop  Alexandria        50000
9      Omar    Laptop        Giza        25000
13     Mona    Laptop        Giza        25000
15     Omar  Keyboard       Cairo         6000

In [ ]:
# 78. Group the filtered DataFrame by City and find total sales for each city

In [ ]:
filtered_df.groupby("City")["Total_Price"].sum()

City
Alexandria    50000
Cairo         31000
Giza          57000
Name: Total_Price, dtype: int64

In [ ]:
# 79. Sort the grouped result from highest sales to lowest sales.

In [ ]:
filtered_df.groupby("City")["Total_Price"].sum().sort_values(ascending=False)

City
Giza          57000
Alexandria    50000
Cairo         31000
Name: Total_Price, dtype: int64

In [ ]:
# 80. Write one sentence explaining which city performed best
# Giza performed the best because it generated the highest total sales.

In [ ]:
# 81. Create a function that receives Total_Price and returns "High Value" if the total is >=10000, otherwise "Normal Value". Create a new column called Order_Value.

In [ ]:
def order_value(total):
  if total >= 10000:
    return "High Value"
  else:
    return "Normal Value"

df["Order_Value"] =df["Total_Price"].apply(order_value)
df

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price,Order_Size,Payment_Type,Price_Level,Order_Value
0,101,Sara,Laptop,Computers,1,25000,Cairo,Card,Ahmed,25000,Small,Electronic Payment,Expensive,High Value
1,102,Ali,Mouse,Accessories,3,500,Alexandria,Cash,Laila,1500,Small,Cash Payment,Affordable,Normal Value
2,103,Mona,Keyboard,Accessories,2,1200,Cairo,Card,Ahmed,2400,Small,Electronic Payment,Affordable,Normal Value
3,104,Omar,Monitor,Screens,1,7000,Giza,Card,Khaled,7000,Small,Electronic Payment,Expensive,Normal Value
4,105,Sara,Mouse,Accessories,5,500,Cairo,Cash,Laila,2500,Large,Cash Payment,Affordable,Normal Value
5,106,Youssef,Laptop,Computers,2,25000,Alexandria,Card,Ahmed,50000,Small,Electronic Payment,Expensive,High Value
6,107,Mona,Monitor,Screens,1,7000,Giza,Cash,Khaled,7000,Small,Cash Payment,Expensive,Normal Value
7,108,Ali,Keyboard,Accessories,4,1200,Cairo,Card,Laila,4800,Large,Electronic Payment,Affordable,Normal Value
8,109,Nour,Mouse,Accessories,2,500,Alexandria,Cash,Ahmed,1000,Small,Cash Payment,Affordable,Normal Value
9,110,Omar,Laptop,Computers,1,25000,Giza,Card,Khaled,25000,Small,Electronic Payment,Expensive,High Value
10,111,Sara,Keyboard,Accessories,3,1200,Cairo,Card,Laila,3600,Small,Electronic Payment,Affordable,Normal Value
11,112,Nour,Monitor,Screens,2,7000,Alexandria,Cash,Ahmed,14000,Small,Cash Payment,Expensive,High Value
12,113,Youssef,Mouse,Accessories,6,500,Cairo,Card,Khaled,3000,Large,Electronic Payment,Affordable,Normal Value
13,114,Mona,Laptop,Computers,1,25000,Giza,Card,Ahmed,25000,Small,Electronic Payment,Expensive,High Value
14,115,Ali,Monitor,Screens,2,7000,Alexandria,Cash,Laila,14000,Small,Cash Payment,Expensive,High Value
15,116,Omar,Keyboard,Accessories,5,1200,Cairo,Card,Khaled,6000,Large,Electronic Payment,Affordable,Normal Value
16,117,Sara,Laptop,Computers,1,25000,Giza,Cash,Ahmed,25000,Small,Cash Payment,Expensive,High Value
17,118,Nour,Mouse,Accessories,3,500,Alexandria,Card,Laila,1500,Small,Electronic Payment,Affordable,Normal Value
18,119,Youssef,Monitor,Screens,2,7000,Cairo,Cash,Khaled,14000,Small,Cash Payment,Expensive,High Value
19,120,Mona,Keyboard,Accessories,4,1200,Giza,Card,Ahmed,4800,Large,Electronic Payment,Affordable,Normal Value

In [ ]:
# 82. Count the number of High Value and Normal Value orders

In [ ]:
df["Order_Value"].value_counts()

Order_Value
Normal Value    12
High Value       8
Name: count, dtype: int64

In [ ]:
# 83. Find total sales for each Order_Value category

In [ ]:
df.groupby("Order_Value")["Total_Price"].sum()

Order_Value
High Value      192000
Normal Value     45100
Name: Total_Price, dtype: int64

In [ ]:
# 84. Find the average quantity for each Order_Value category

In [ ]:
df.groupby("Order_Value")["Quantity"].mean()

Order_Value
High Value      1.50
Normal Value    3.25
Name: Quantity, dtype: float64

In [ ]:
# 85. Find all High Value orders from Cairo

In [ ]:
df[(df["Order_Value"] == "High Value") & (df["City"] == "Cairo")]

,Order_ID,Customer,Product,Category,Quantity,Price,City,Payment_Method,Salesperson,Total_Price,Order_Size,Payment_Type,Price_Level,Order_Value
0,101,Sara,Laptop,Computers,1,25000,Cairo,Card,Ahmed,25000,Small,Electronic Payment,Expensive,High Value
18,119,Youssef,Monitor,Screens,2,7000,Cairo,Cash,Khaled,14000,Small,Cash Payment,Expensive,High Value

In [ ]:
df.columns

Index(['Order_ID', 'Customer', 'Product', 'Category', 'Quantity', 'Price',
       'City', 'Payment_Method', 'Salesperson', 'Total_Price', 'Order_Size',
       'Payment_Type', 'Price_Level', 'Order_Value'],
      dtype='object')